# Generated by Django 5.2.8 on 2025-11-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_description', models.CharField(max_length=400)),
                ('has_prereq', models.ManyToManyField(to='courseoptimizer.course')),
            ],
        ),
    ]
